### ISSUE TITLE
TAgrading access to submitted homeworks before deadline

### ISSUE THREAD

**Issue by bmcutler** [RCOS-Grading-Server/HWserver#117]
Right now, TAs are locked out of the grading page for a homework until 2 days past the submission deadline (to allow for late days).

Instead, let's allow them to view the files a student has submitted as it will appear when grading opens, but the rubric will be unavailable/greyed out.  This will help TAs help students who have submission problems.  (An alternate to ssh access & examining files directly).

**Comment by MasterOdin** [comment]
This should also actually use the number of late days for the assignment instead of being hardcover at 2 days + 8 hours.

**Comment by MasterOdin** [comment]
All created rubrics appear in the dropdown and can be selected. However, for homeworks that are not yet open for grading, they'll say "(Gradable: ##") with then a date there. If navigated to the actual rubric form, there's no way to submit the form nor change any of the select boxes. User should receive error if they try to submit an unopened assignment as well.

Assignment being "open" is determined by due date + number of available late days.
