### ISSUE TITLE
Facilitate TA viewing/grading the lab/homework of a student in another lab section/grading section

### ISSUE THREAD

**Issue by bmcutler** [RCOS-Grading-Server/HWserver#118]
Upload only works for first time population of the database (seems to work ok, but only if there are no duplicates).

Would like to run with the same list (provided by the registrar) after add date & after drop date.
If a student is not on the list, reassign them to the "drop" section.  If a student is in a different section switch the section.

Also would like webform for manual section addition & section switch (accessible by TAs).  Independent studies are not on the sheet from the registrar, but they are assigned a section (should be on lab sheets).  So these students shouldn't be moved to the drop list.

- [ ] Allow TA viewing/grading the homework of a student in grading section assigned to another TA 
       (right now they can, they just manual edit the username in the URL)  (make it obvious how to)

- [ ] Allow TA to enter makeup checkpoint for a student not in their lab section (make it obvious how to)
  
- [ ] Allow TA to sub for and data enter checkpoints for the whole lab section (make it obvious how to)

**Comment by MasterOdin** [comment]
I guess this involves two changes:
1) Add control for what section missing students on classlist get moved to (and if they should)
2) Add new column that reads "manually added/edited" with a control to ignore these students'section if they don't appear in the classlist or just go to a different section without properly switching

**Comment by MasterOdin** [comment]
Haven't made a webform for section addition or section switch for TAs. Will need to discuss in person best way to implement this.

**Comment by bmcutler** [comment]
Editing student->section assignment is on checklist for Issue #122.
Creating/Maintaing course enrollment related to Issue #120.

**Comment by bmcutler** [comment]
- [ ] Allow TA viewing/grading the homework of a student in grading section assigned to another TA 
       (right now they can, they just manual edit the username in the URL)  (make it obvious how to)

- [ ] Allow TA to enter makeup checkpoint for a student not in their lab section (make it obvious how to)
  
- [ ] Allow TA to sub for and data enter checkpoints for the whole lab section (make it obvious how to)
