### ISSUE TITLE
Expanding Types of Gradeables (Was: Create "Quizzes" Page)

### ISSUE THREAD

**Issue by MasterOdin** [RCOS-Grading-Server/HWserver#131]
Duplicate "Tests" pages to have a "quizzes" page.

**Comment by bmcutler** [comment]
Instead, I propose that we allow the instructor to specify both the "id" (no spaces allowed, must be unique) and the "name" (spaces allowed, but no double quotes).  If the id starts with "quiz", "test", or "exam" (or maybe some other agreed upon terms) then the rainbow grades code will sort these gradeables into buckets.

Similarly, allow the instructor to name give an "id" and "name" to labs.  If the prefix starts with "lab" or "reading" (or maybe "participation"), Rainbow Grades will know what to do.

And for rubrics, we can have "assignment", "hw", "homework", "project" be the magic prefixes for ids.

(Only Rainbow Grades will care about the prefix, but I suppose the TAgrading interface could suggest this id convention)

**Comment by MasterOdin** [comment]
This was suitably accomplished (at least for now) in the following commits: 2c1d2ad1efdebbb461b88ab8dc18ba07885e38f1, 318ac81b488826b7f7231442ef4ef7e1998fde4f, and c3a595afa8a7c5f25817b23909dcf3eced3a3251
