### ISSUE TITLE
Increase size of TA comment in homework rubric

### ISSUE THREAD

**Issue by bmcutler** [RCOS-Grading-Server/HWserver#135]
We hit a limit of 255 characters.   The error message to the instructor was unhelpful (the answer was in the ta grading log, but not obvious initially).

Let's both increase the max allowed size for that field & improve the error message when exceeded.

**Comment by MasterOdin** [comment]
Run:
ALTER TABLE questions ALTER COLUMN question_message TYPE character varying;
ALTER TABLE questions ALTER COLUMN question_grading_note TYPE character varying;

against all databases to resolve this issue.

**Comment by MasterOdin** [comment]
Ran queries against all classes and made a commit for the new schema.
