### ISSUE TITLE
Intermittent false-positive error in building course

### ISSUE THREAD

**Issue by pbailie** [RCOS-Grading-Server/HWserver#166]
After receiving updated code from Master (build f74378d -> f9cff3c)...

During building my test course, one of my test assignments that used to build OK would no longer build, generating a false positive error.  (note that both AUTO_POINTS and test cases had 20 points)
```ERROR: Automated Points do not match testcases.20!=0```

I changed AUTO_POINTS to 10, which is a deliberate mismatch with test cases still totaling 20.  This time I got a proper error message.
```ERROR: Automated Points do not match testcases.10!=20```

I changed AUTO_POINTS back to 20, and the error cleared.

Attached: config.h that triggered the error.  
[config.h.txt](https://github.com/RCOS-Grading-Server/HWserver/files/2816/config.h.txt)

**Comment by bmcutler** [comment]
Can you reproduce this error?  I don't think any recent commits should affect this portion of the system.
I suspect it was a build error (file/directory timestamps/Makefile confusion).
