### ISSUE TITLE
Grading GUI doesn't show some files

### ISSUE THREAD

**Issue by yknot** [RCOS-Grading-Server/HWserver#175]
I was grading Data Structures homework and it doesn't show all of the files the student submitted. It was missing a ".hpp" file, which admittedly is a mistake by the student, but it wasn't showing those files even though they were on the server.

**Comment by MasterOdin** [comment]
@bmcutler needs to add the "hpp" file extension to the allowed file extensions in the configuration of the application for her class if she wants it to show up. I'm not sure we always want to show all files regardless of extension on submissions.

**Comment by MasterOdin** [comment]
So the solution here is lifiting the requirement of only allowing certain types and allow all types, with the knowledge that some types (such as images, pdf, and other binary formats) are going to be broken if they try to get viewed, however there's no actual security issue with displaying the binary output from them.

**Comment by MasterOdin** [comment]
This was accomplished already.
