### ISSUE TITLE
README filename case sensitivity and validator error

### ISSUE THREAD

**Issue by pbailie** [RCOS-Grading-Server/HWserver#177]
Currently, the auto grader, when checking for the existence of a readme, can only detect the filename "README.txt".  The TestCase::MakeFileExist() object's expected file parameter must also match case (as "README.txt").

BUG: Should lowercase "readme.txt" be submitted, the validator will miss the file, even when config.h's TestCase::MakeFileExist() object has a matching lowercase "readme.txt" as the expected file parameter.

Hypothetically, there can be filename confusion between the student submitter and the homework server.  Many students will do their homework on either Windows or Macintosh platforms.  The default Windows filesystem (NTFS) and default Macintosh file system (Mac OS Extended) are **NOT** case sensitive.  e.g. "readme.txt" and "README.txt" are the same file.  But the homework server runs on Linux.  Probably the most commonly used filesystem on Linux is EXT4, which is case sensitive.  e.g. "readme.txt" and "README.txt" are different files.

**Comment by pbailie** [comment]
*  Validator code logic _appears_ to be OK.  Simple if statement checks file for existence via ```access()``` function (defined in ```unistd.h```).  **Anomaly**: Conditional result is ```-1``` when lowercase "readme.txt" is the filename argument and "readme.txt" is the submitted file.  Expected result should be ```0```.  
Check ```GIT_CHECKOUT_HWserver/grading/main_validator.cpp : line 104```.
* Submitted readme.txt file does exist in data ```{course}/submissions/{assignment}/{student}/{upload_revision}```
* General behavior of ```access()``` function appears correct when tested externally.

**Comment by bmcutler** [comment]
At this time we cannot support case insensitive file names. 
The server is Linux and students should learn the importance of case sensitive file name requirements. 

If this becomes a critical bug we can re-open this issue.
