### ISSUE TITLE
create new rubric, default to previous rubric #?

### ISSUE THREAD

**Issue by bmcutler** [RCOS-Grading-Server/HWserver#179]
I went to create a new rubric for HW3, and the name defaulted to Homework 2 and the id defaulted to hw02.  I changed to "Homework 3" and "hw03".  Just to test, after finish hw3, I clicked to create a 4th rubric and it also defaulted to homework 2 and hw02.

(defaults can be improved, thanks!)

**Comment by MasterOdin** [comment]
This should have been sufficiently improved for the time being.
