### ISSUE TITLE
JSON Decode Failure

### ISSUE THREAD

**Issue by pbailie** [RCOS-Grading-Server/HWserver#196]
A JSON decode failure can happen when loading a homework submit page when the config.h is coded in a special way.

In this example (simple exercise of calculating Fibonacci numbers) -- when asked what Fibonacci sequence element to calculate, `fifteen` is sent through STDIN. This should be an error case as fifteen is a string when an integer is expected.  Therefore, the only output in STDOUT is the user prompt, `Please enter nth Fibonacci element: `.  STDERR is expected to output the string `error`.  

Test Case in config.h
```C++
TestCase::MakeTestCase(
	"\"fifteenth\" fibonacci number",
	"fifteen",
	"./a.out <test4_stdin.txt",
	TestCasePoints(5),
	{
		new TestCaseComparison(
			&myersDiffbyLinebyChar,
			"STDOUT.txt",
			"Standard OUTPUT (STDOUT)",
			"test4_stdout.txt",
			1.0
		),

		new TestCaseTokens(
			&searchToken,
			"STDERR.txt",
			"Standard ERROR (STDERR)",
			std::vector<std::string>(
				1,
				std::string("error")
			)
		)
	}
)
```
What happens is this test case compiles A-OK, but the autograder does not provide any grading feedback to the student.  An (incorrect) grade with no error message shows in the autograde log.

Log  (note that grade on 2nd line isn't correct.  Should be 25/25.)
```
Mon Oct 12 18:50:47 EDT 2015 | 21569  |       | f15__csci1000__cpp_fibonacci_stdin__student__1     | wait:      4 sec | 
Mon Oct 12 18:50:48 EDT 2015 | 21569  |       | f15__csci1000__cpp_fibonacci_stdin__student__1     | grade:     1 sec | Automatic grading total:                           20 / 25
```
When the student reloads to the submission page, the page is filled with JSON decode error messages.

JSON Decode Error
![json decode error](https://cloud.githubusercontent.com/assets/12703624/10441776/a18ce74a-711a-11e5-8b6e-e43d8c8dcd5f.png)

Due to extremely sparse documentation on config.h, this was an attempted interpretation on configuring a homework test case for an edge error case.  If this config is invalid by spec, please still consider that a potential and intimidating JSON decode error goes _uncaught_ on the website view.

**Comment by MasterOdin** [comment]
Could you attach the json file text that was generated?

**Comment by pbailie** [comment]
Attachment:  [JSON_error.txt](https://github.com/RCOS-Grading-Server/HWserver/files/12705/JSON_error.txt)

**Comment by MasterOdin** [comment]
So the problem is that we don't properly escape strings when constructing the JSON object, so if you use a ```"``` in your test name, diff name, etc. the produced JSON will contain an error, and hence it cannot be decoded (and we should never expect it to). 

I would say tell people to not use ```"``` in the config.h strings till #39 is done at which point this issue should be taken care of as well.

**Comment by pbailie** [comment]
Thank you.  My testing confirms that the issue is caused by escaping ```"```.
