### ISSUE TITLE
Allow "cancellation" of homework submission

### ISSUE THREAD

**Issue by bmcutler** [RCOS-Grading-Server/HWserver#231]
2 usage cases:

* a student may have intended to completely skip one assignment, but accidentally uploaded something (could even have been the next homework).  They don't want the TAs to grade the uploaded material, and more importantly don't want to be charged late days for that submission.

* a student may have intentionally uploaded material to the server one or more days after the submission deadline, but after seeing the autotesting results/automated grade choose to retract/cancel the submission and save their late days for a future assignment.

note: the submission will still be archived.

tasks:

- [x] add a button to the UI.  
- [x] decide on the representation.  currently "active assignment" counter begins at 1.  So we chould choose 0 or -1.
- [x] detect cancelled/retracted submission in ta grading code and display appropriate message to TA.
- [ ] check for other pieces of the code that might be affected.

**Comment by bmcutler** [comment]
Decided...   "active assignment" will be "-1",  Instead of "No submission", TA will see "Cancelled Submission" a 0 will be awarded and no late days charged.

**Comment by MasterOdin** [comment]
We've gone with marking the active assignment as 0 when cancelling an assignment (as the Grading code already uses -1 to mean no submission). This was added to the grading code in 7aae565dfee077ef5722aae0507e5e748597c263.

**Comment by bmcutler** [comment]
The submission side now allows cancellation and stores it as '0'.
3a87e004d0c00e06f99cf0c5c4fe324c4db9ccd1

a bit more debugging needed so the TA sees "cancelled homework" instead of "no submission"
