### ISSUE TITLE
Have different starting "grading page" for administrators viewing homeworks

### ISSUE THREAD

**Issue by MasterOdin** [RCOS-Grading-Server/HWserver#262]
Right now, when an administrator views a homework, they're shown a box that says "You've finished grading the homework!" and then have to click a button to get taken an overview page where they can then see the grading progress of the homework. This isn't very initutive and should be changed to either:
[a] Show grading progress in each grading section
[b] Go straight to the grading overview page and skip this page

@bmcutler which would you think instructors would want most (or is there an additional better option)?

**Comment by bmcutler** [comment]
I vote for option [b].  I usually go and scan to see what fraction of grading is completed.
An enhancement that would be very helpful would add the name of the TAs assigned to each section in that gray header bar (so I know not only that grading section X is incomplete, but that I need to pester TA Y to complete that grading).

**Comment by MasterOdin** [comment]
I would think option [a] would deliver that information much more quickly (as I'm envisioning the page being something like:

Grading Done: 39 / 80 students done
Grading Section 1 (Bob): 12 / 20 students
Grading Section 2 (Mike): 2 / 20 students
Grading Section 3 (Mike, Sally): 20 / 20 students
Grading Section 4 (Phillip): 5 / 20 students

[Select Different Homework] [Homework Overview]

(the bottom two things being buttons)

**Comment by bmcutler** [comment]
[a] looks great too!
