### ISSUE TITLE
Cannot provision Vagrant development VM (at least in Windows)

### ISSUE THREAD

**Issue by pbailie** [RCOS-Grading-Server/HWserver#297]
This problem was first noted in Issue #290.  Although #290 is fixed, there are other problems with provisioning a Vagrant development VM server.  I produced this issue in Windows 7 SP1 64-bit using VirtualBox 5.0.14 and Vagrant 1.8.1.

Numerous script errors involving `sed` command are thrown during the provisioning process.  Here is a snippet example:
```
==> default: sed: can't read __CONFIGURE__FILLIN__HSS_INSTALL_DIR__/bin/untrusted_execute.c: No such file or directory
```
Also looking at the shared folder (`/vagrant`) showed possible data corruption as errant files and folders were seen in the shared folder, both on the host and guest _after_ provisioning had failed.
```bash
drwxrwxrwx  1 vagrant vagrant  4096 Mar  6 21:16 __CONFIGURE__FILLIN__HSS_DATA_DIR__
drwxrwxrwx  1 vagrant vagrant     0 Mar  6 21:16 __CONFIGURE__FILLIN__HSS_INSTALL_DIR__
```
and
```bash
-r-xr-xr-x  1 vagrant vagrant 18790 Mar  6 21:16 sed0CDY9R
-r-xr-xr-x  1 vagrant vagrant 18771 Mar  6 21:16 sed0nz7kj
-r-xr-xr-x  1 vagrant vagrant 18798 Mar  6 21:16 sed2ME1QK
-r-xr-xr-x  1 vagrant vagrant 18747 Mar  6 21:16 sed5JLBRu
-r-xr-xr-x  1 vagrant vagrant 18771 Mar  6 21:16 sedC7IkOl
-r-xr-xr-x  1 vagrant vagrant 18745 Mar  6 21:16 sedcCVWGz
-r-xr-xr-x  1 vagrant vagrant 18748 Mar  6 21:16 seddIRIlC
-r-xr-xr-x  1 vagrant vagrant 18778 Mar  6 21:16 sede1WYOP
-r-xr-xr-x  1 vagrant vagrant 18764 Mar  6 21:16 sedIfC9Yt
-r-xr-xr-x  1 vagrant vagrant 18772 Mar  6 21:16 sedM77Gvn
-r-xr-xr-x  1 vagrant vagrant 18784 Mar  6 21:16 sedNCGITu
-r-xr-xr-x  1 vagrant vagrant 18768 Mar  6 21:16 sedOgE6vr
-r-xr-xr-x  1 vagrant vagrant 18770 Mar  6 21:16 sedPMH7zZ
-r-xr-xr-x  1 vagrant vagrant 18771 Mar  6 21:16 sedPPnLaX
-r-xr-xr-x  1 vagrant vagrant 18760 Mar  6 21:16 sedQpBPnc
-r-xr-xr-x  1 vagrant vagrant 18760 Mar  6 21:16 sedr3U9S9
-r-xr-xr-x  1 vagrant vagrant 18788 Mar  6 21:16 sedrff19p
-r-xr-xr-x  1 vagrant vagrant 18788 Mar  6 21:16 sedrn45Os
-r-xr-xr-x  1 vagrant vagrant 18770 Mar  6 21:16 seds5w4ih
-r-xr-xr-x  1 vagrant vagrant 18775 Mar  6 21:16 seduGIHeN
-r-xr-xr-x  1 vagrant vagrant 18770 Mar  6 21:16 sedvSjGRe
-r-xr-xr-x  1 vagrant vagrant 18765 Mar  6 21:16 sedX9CNy7
-r-xr-xr-x  1 vagrant vagrant 18770 Mar  6 21:16 sedYoUo14
-r-xr-xr-x  1 vagrant vagrant 18750 Mar  6 21:16 sedZAZpfx
```
These files contain pieces of the HWserver install script.  Here is a snippet from `sed0CDY9R`.
```bash
# make the directory (has a different name)
mkdir -p $HSS_INSTALL_DIR/bin
chown root:$COURSE_BUILDERS_GROUP $HSS_INSTALL_DIR/bin
chmod 751 $HSS_INSTALL_DIR/bin

# copy all of the files
rsync -rz  $HSS_REPOSITORY/bin/*   $HSS_INSTALL_DIR/bin/
#replace necessary variables in the copied scripts
replace_fillin_variables $HSS_INSTALL_DIR/bin/create_course.sh
replace_fillin_variables $HSS_INSTALL_DIR/bin/grade_students.sh
replace_fillin_variables $HSS_INSTALL_DIR/bin/grading_done.sh
replace_fillin_variables $HSS_INSTALL_DIR/bin/regrade.sh
replace_fillin_variables $HSS_INSTALL_DIR/bin/build_course.sh
replace_fillin_variables $HSS_INSTALL_DIR/bin/build_homework_function.sh
replace_fillin_variables $HSS_INSTALL_DIR/bin/fake_submit_button_press.sh
replace_fillin_variables $HSS_INSTALL_DIR/bin/untrusted_execute.c
replace_fillin_variables $HSS_INSTALL_DIR/bin/setcsvfields
```

**Comment by pbailie** [comment]
Could not reproduce problem on my Macintosh workstation (OS X 10.9.5, Virtualbox 4.3.34, Vagrant 1.8.1).

**Comment by pbailie** [comment]
Error reproduced on Windows 7 SP1, Virtualbox 4.3.30, Vagrant 1.8.1.

**Comment by pbailie** [comment]
Point of failure starts here in `./setup/install_system.sh`.  (block starts at line 331)
```bash
if [ ${VAGRANT} == 1 ]; then
    echo -e "localhost
    hsdbu
    hsdbu
    https://192.168.56.103
    svn+ssh:192.168.56.102" | source ${HWSERVER_DIR}/CONFIGURE.sh
else
```
This invokes `/vagrant/CONFIGURE.sh` (note that /vagrant is a shared folder from the host where the HSS repo was cloned to).  Failure occurs on line 105:
```bash
cp $HSS_REPOSITORY/bin/INSTALL_template.sh $HSS_REPOSITORY/INSTALL.sh
```
This error message gets purged beyond the `cmd.exe`'s scroll-back cache.  I found it by redirecting all Vagrant output to a text file.
```
cp: cannot create regular file `/vagrant/INSTALL.sh`: Operation not permitted
```
In this case, a file was to be copied from the host, back to the host, but by way of the guest.  This may have violated a sandbox with the Virtualbox/Windows relationship.

I will investigate this further, but we may need to be prepared to find an alternative workaround (clone github repo directly within the VM rather than use a shared folder).

**Comment by pbailie** [comment]
Escalated `cmd.exe` to run as administrator and attempted to create and provision Vagrant VM.  Same error.

**Comment by MasterOdin** [comment]
I would rate cloning the github repo within the vagrant box instead of using the shared folder as a worst case solution going against the ideology of using vagrant. 

I would like to see tests using cygwin as well as playing with the permissions of the mounted folder:
```
config.vm.synced_folder ".", "/vagrant", owner: "vagrant", group: "vagrant", mount_options: ["dmode=775,fmode=775"]
```

**Comment by pbailie** [comment]
Merge request #321 open.

**Comment by pbailie** [comment]
Merge complete
