### ISSUE TITLE
Add semester to grading server

### ISSUE THREAD

**Issue by MasterOdin** [RCOS-Grading-Server/HWserver#307]
We should be specifying both semester and course in both grading and submission servers. This would allow us to more easily go back and look at past semesters assuming the databases remained.

Additionally, all config files would then take on the format ```hss_coursecode_semester.php``` modelling after the DB. An example of this would be CSCI1100 for S16 would be ```hss_csci1100_s16.php```. @bmcutler or @pbailie have any issue with this suggestion and for doing it after the semester has ended?

**Comment by SLiNv** [comment]
Doesn't the CS department clean up the server after every semester? Just guessing...

**Comment by MasterOdin** [comment]
How RPI handles its servers is not necessarily how other schools might want to handle their servers. Right now you could potentially go indefinitely backwards on the submission side of things but we can only handle one semester per course on the grading side of things (unless you name your course "f15_csci1100" or something, but that's not very wieldy).

**Comment by MasterOdin** [comment]
Done in start of 1.0 branch as of 02c2900c5010f5175765970316203686d1c6c88b
