### ISSUE TITLE
Unconfusable Rubric IDs

### ISSUE THREAD

**Issue by bmcutler** [RCOS-Grading-Server/HWserver#327]
Request:  Get rid of the "rubric_id" sequence in the rubrics table.  Use rubric_submission_id instead.  rubric_submission_id is unique.

If a rubric is deleted or if a course starts with "homework 0" or the rubric id vs the rubric_submission_id can be "off by one (or more)" and is just plain confusing.  

It would be much less confusing to use rubric_submission_id in the late_day_exceptions table.

[ Yes, it will be better when there's a webform to enter this data, but debugging is still harder than it needs to be. ]

**Comment by MasterOdin** [comment]
rubric_submission_id would be the primary key of the table and we replace all foreign key constraints on rubric_id to point to rubric_submission_id in dependent tables.

**Comment by MasterOdin** [comment]
This will also be done for the labs table (for lab number) and others (for other_id) since they're already required to be unique fields.
