### ISSUE TITLE
Add Java language functionality (Junit test suite)

### ISSUE THREAD

**Issue by kmcnellis** [RCOS-Grading-Server/HWserver#63]

**Comment by MasterOdin** [comment]
I'm curious to know why you've put JUnit here as there's no java code (and I'd suggest not building a JUnit runner for PHP/C++).

It'd be a lot easier to use [googletest](https://code.google.com/p/googletest/) with [PHPUnit](https://phpunit.de/) and maybe [http://www.jsunit.net/](JSUnit). We could then tie this together within a bash script to run the test suite within Travis/locally.

For C++, there's also Boost.Test, Cpptest, and xUnit++, but I've only ever heard anything about gtest.

**Comment by MasterOdin** [comment]
Email to Barb about this:

So here's a very simple example of how you'd setup JUnit for this software design class submissions.

The files in java.zip are:
TestClass.java (contains a simple addition function)
TestClassTester.java (contains one working test)
TestClassTester2.java (contains one working test and one wrong test)

Once you cd into the java directory contained in the attached zip file, you'd run the following commands:

javac -cp junit-4.12.jar *.java
java -cp junit-4.12.jar:hamcrest-core-1.3.jar:. org.junit.runner.JUnitCore TestClassTester
java -cp junit-4.12.jar:hamcrest-core-1.3.jar:. org.junit.runner.JUnitCore TestClassTester2

java.txt shows the output from running those commands, with the first Tester working fine and the second one throwing an AssertionError exception. You'd also have to be able to capture other types of exceptions for code that is broken or didn't account for some edge case which causes a NullPointer or whatever.

Attached files:
[java.zip](https://dl.dropboxusercontent.com/u/6782048/java.zip)
[java.txt](https://dl.dropboxusercontent.com/u/6782048/java.txt)
