### ISSUE TITLE
max_output_size should apply on a per output basis, not all outputs together

### ISSUE THREAD

**Issue by MasterOdin** [RCOS-Grading-Server/HWserver#71]
Right now, specifying a max_output_size of 5000 allows, for example, one output file to use all 5000 bytes or 5 files to each use 1000 bytes each. It should be that each submission is allowed 5000 bytes.

This would be a real issue if on sheer luck I were to set the size such that it's equivalent to exactly the max size of the outputs such that unless the student was perfectly right, some of their outputs would not give useable feedback (as it'd just display "MAX SIZE EXCEEDED" or whatever) which is bad and would lead to unfortunate complaints.

**Comment by sihsob** [comment]
Difficult to complete

**Comment by bmcutler** [comment]
We have implemented the file size limit with setrlimit, RLIMIT_FSIZE:
http://linux.die.net/man/2/setrlimit

If any one file created or appended by the process exceeds the limit, the process is terminated (actually, sent a signal).

It would not be easy to set a limit on the sum of file sizes.
