### ISSUE TITLE
score of 0 displayed for non scored homeworks

### ISSUE THREAD

**Issue by bmcutler** [RCOS-Grading-Server/HWserver#78]
The pulldown menu displays a score even if there are no autograding points.  This is confusing since its right next to the 'days late' message.

![buggy_pulldown](https://cloud.githubusercontent.com/assets/5871417/6998118/08034968-dba4-11e4-943b-1383b602c511.png)

**Comment by MasterOdin** [comment]
submitted pull request for review that doesn't show the 0 if the HW's points visible is <= 0 (as the information isn't useful to the student).

So it'd now display:
```Version #2  Days Late: 1  ACTIVE```

**Comment by kmcnellis** [comment]
The pull request didn't go through

**Comment by MasterOdin** [comment]
https://github.com/RCOS-Grading-Server/HWserver/pull/79
