### ISSUE TITLE
Have grading queue work more fairly between courses

### ISSUE THREAD

**Issue by MasterOdin** [RCOS-Grading-Server/HWserver#88]
Right now, all classes submit to the same grading queue that acts as FIFO. This means that if one course has a very long/slow queue process, this will block all other classes from being graded till it is done. There should be a fairer process for running the queue (ex. do one assignment per course that's submitted, in a cycle) so as to prevent this block.

Quote from email from Barb about it as well
> In addition to reorganizing how we work through the queue, the message
to the student needs to be adjusted.  Right now it just says
"currently being graded" if the assignment is ungraded, but it should
also have a state "waiting in queue to be graded" and maybe even your
position in the queue and time to start grading (hard to estimate
accurately).

**Comment by bmcutler** [comment]
When we need to reprocess alot of students (correcting a problem with the grading scripts after submission has started, or when running a "contest"), the reprocessing-homeworks should have a flag/nice bit set that allows interactively-submitted-homeworks to jump in front of them.

If a student submits the same homework several times in quick succession, we may want to only grade their most recent submission and set the flag/nice bit for the earlier ones.

**Comment by MasterOdin** [comment]
This was accomplished over the summer and can be closed.
