### ISSUE TITLE
Large diff files freezes on hover

### ISSUE THREAD

**Issue by MasterOdin** [RCOS-Grading-Server/HWserver#96]
Below is diff file with expected file. When hovering over the empty student's submission, there is a noticeable lag to have the highlighting appear/disappear. Doesn't seem to happen when hovering over the expected input lines.

Diff file: http://pastebin.com/C4gsHGBs
Expected input: http://pastebin.com/77X9Sxbh

**Comment by kmcnellis** [comment]
What method was used to create this diff?

**Comment by MasterOdin** [comment]
myersDiffbyLinebyChar

**Comment by sihsob** [comment]
Merge/switch to diff viewer in ta grading

**Comment by bmcutler** [comment]
Closing this issue
